version: 2.1

parameters:
  ref_to_build:
    type: string
    default: ""

jobs:
  build:
    machine:
      # Fixed to this version due to issues with Git LFS
      # https://discuss.circleci.com/t/git-lfs-broken-in-recent-ubuntu-20-04-machine-images-arm64/46473/1
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run: git clone --depth 1 --branch << pipeline.parameters.ref_to_build >> https://github.com/signalapp/Signal-Desktop .
      - run: git clone https://github.com/dennisameling/signal-desktop-automation ./tmp-automation-release-scripts
      - run:
          # This uses the .nvmrc from Signal Desktop to determine the right version to use
          name: Install NodeJS
          command: |
            nvm install
            nvm use
            nvm alias default $(nvm current)
            npm install --location=global yarn
      - run:
          # https://discuss.circleci.com/t/changed-behaviour-of-nvm-alias-after-migrating-to-new-machine-image/42965
          name: "Enforce nvm use default"
          command: |
            echo "nvm use default" >> $BASH_ENV
      - run: sudo apt-get update && sudo apt-get install xvfb libgbm-dev build-essential ruby git-lfs
      - run: git lfs install
      - run:
          name: Install FPM (for packaging)
          command: gem install fpm
      - run:
          name: Prepare release signing
          command: |
            echo $SIGN_RELEASE_PUBLIC_KEY >> public.key
            echo $SIGN_RELEASE_PRIVATE_KEY >> private.key
      # The script below ensures that we overwrite some defaults from the official Signal repo
      - run: PUBLIC_KEY="$SIGN_RELEASE_PUBLIC_KEY" SIGNAL_DIR="$CIRCLE_WORKING_DIRECTORY" node ./tmp-automation-release-scripts/patch-files.mjs
      # We need git-lfs for the better-sqlite3 dependency
      - run: which node && which npm && which yarn && which fpm && yarn install --frozen-lockfile
      - run: yarn generate
      - run: yarn prepare-beta-build
      - run:
          command: export USE_SYSTEM_FPM=true && yarn build
          environment:
            DISABLE_INSPECT_FUSE: on
      - run: xvfb-run --auto-servernum yarn test-node
      - run:
          command: xvfb-run --auto-servernum yarn test-electron
          environment:
            LANG: en_US
            LANGUAGE: en_US
      - run:
          name: Copy release artifacts as store_artifacts doesn't support wildcards
          command: mkdir -p release-binaries && cp release/signal-desktop-unofficial* ./release-binaries
      - store_artifacts:
          path: "release-binaries"

workflows:
  signal:
    when: << pipeline.parameters.ref_to_build >>
    jobs:
      - build