version: 2.1

parameters:
  ref_to_build:
    type: string
    default: ""

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.10.1
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: python --version
      - run: git clone --depth 1 --branch << pipeline.parameters.ref_to_build >> https://github.com/signalapp/Signal-Desktop .
      - run: git clone https://github.com/dennisameling/signal-desktop-automation ./tmp-automation-release-scripts
      - run: sudo apt-get update && sudo apt-get install xvfb git-lfs build-essential ruby
      - run: git lfs install
      - run: sudo gem install fpm --force
      - run:
          name: Prepare release signing
          command: |
            echo $SIGN_RELEASE_PUBLIC_KEY >> public.key
            echo $SIGN_RELEASE_PRIVATE_KEY >> private.key
      - run:
          name: Install NodeJS + Yarn
          command: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install
            nvm use
            nvm alias default $(nvm current)
            npm install --location=global yarn
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      # The script below ensures that we overwrite some defaults from the official Signal repo
      - run: PUBLIC_KEY="$SIGN_RELEASE_PUBLIC_KEY" SIGNAL_DIR="$CIRCLE_WORKING_DIRECTORY" node ./tmp-automation-release-scripts/patch-files.mjs
      - run: which node && which npm && yarn install --frozen-lockfile
      - run: yarn generate
      - run: yarn prepare-beta-build
      - run:
          command: yarn build
          environment:
            DISABLE_INSPECT_FUSE: on
            USE_SYTEM_FPM: true
      - run: xvfb-run --auto-servernum yarn test-node
      - run:
          command: xvfb-run --auto-servernum yarn test-electron
          environment:
            LANG: en_US
            LANGUAGE: en_US
      - run:
          command: xvfb-run --auto-servernum yarn test-release
          environment:
            NODE_ENV: production
      - store_artifacts:
          path: "${CIRCLE_WORKING_DIRECTORY}/release/signal-desktop-linux-*"

workflows:
  signal:
    when: << pipeline.parameters.ref_to_build >>
    jobs:
      - build