version: 2.1

parameters:
  ref_to_build:
    type: string
    default: ""

jobs:
  build:
    machine:
      image: ubuntu-2004:2022.04.2
    resource_class: arm.medium
    steps:
      - run: uname -a
      - run: git clone --depth 1 --branch << pipeline.parameters.ref_to_build >> https://github.com/signalapp/Signal-Desktop .
      - run: git clone https://github.com/dennisameling/signal-desktop-automation ./tmp-automation-release-scripts
      - run:
          name: Install NodeJS + Yarn
          command: |
            nvm install
            nvm use
            nvm alias default $(nvm current)
      - run: npm install --location=global yarn
      - run: sudo apt-get update && sudo apt-get install xvfb git-lfs build-essential ruby
      - run: git lfs install
      - run:
          name: Install FPM (for packaging)
          command: gem install fpm
      - run:
          name: Prepare release signing
          command: |
            echo $SIGN_RELEASE_PUBLIC_KEY >> public.key
            echo $SIGN_RELEASE_PRIVATE_KEY >> private.key
      # The script below ensures that we overwrite some defaults from the official Signal repo
      - run: PUBLIC_KEY="$SIGN_RELEASE_PUBLIC_KEY" SIGNAL_DIR="$CIRCLE_WORKING_DIRECTORY" node ./tmp-automation-release-scripts/patch-files.mjs
      - run: which node && which npm && which yarn && which fpm && yarn install --frozen-lockfile
      - run: yarn generate
      - run: yarn prepare-beta-build
      - run:
          command: export USE_SYSTEM_FPM=true && yarn build
          environment:
            DISABLE_INSPECT_FUSE: on
      - run: xvfb-run --auto-servernum yarn test-node
      - run:
          command: xvfb-run --auto-servernum yarn test-electron
          environment:
            LANG: en_US
            LANGUAGE: en_US
      - run:
          command: xvfb-run --auto-servernum yarn test-release
          environment:
            NODE_ENV: production
      - store_artifacts:
          path: "${CIRCLE_WORKING_DIRECTORY}/release/signal-desktop-linux-*"

workflows:
  signal:
    when: << pipeline.parameters.ref_to_build >>
    jobs:
      - build